from typing import Protocol, Any, Sequence, Optional

class RepositoryProtocol(Protocol):
    async def get_by_id(self, id: str) -> Optional[Any]: ...
    async def create(self, data: dict) -> str: ...
    async def update(self, id: str, data: dict) -> bool: ...
    async def delete(self, id: str) -> bool: ...
    async def list(self, *, skip: int = 0, limit: int = 20) -> Sequence[Any]: ...
